version: "3"
services:
  db:
    image: "postgres:12.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "postgres:/var/lib/postgresql/data" 
    ports:
      - "5440:5432" 

  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - .:/onebitexchange
      - gems:/gems
    depends_on:
      - db
    network_mode: bridge  

volumes:
  postgres:
  gems: